// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: PROJECT1/PROJECT1.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

/** hero/hero.proto */

export interface getFirstCommandRequest {
  id: number;
}

export interface getFirstCommandResponse {
  data: string;
  message: string;
  error: string[];
  status: number;
}

export interface getFirstqueryRequest {
}

export interface getFirstqueryResponse {
  data: Hero | undefined;
  message: string;
  error: string[];
  status: number;
}

export interface HeroById {
  id: number;
}

export interface nestedType {
  data: Hero | undefined;
}

export interface Hero {
  id: number;
  name: string;
  error?: string | undefined;
}

export interface Empty {
}

export interface HeroArray {
  hero: Hero[];
}

export interface EnumType {
  payment: EnumType_PAYMENT_SYSTEM;
}

export enum EnumType_PAYMENT_SYSTEM {
  CASH = 0,
  CREDIT_CARD = 1,
  DEBIT_CARD = 2,
  APP = 3,
  UNRECOGNIZED = -1,
}

export interface test {
  hello: string;
}

export interface PROJECT1ServiceClient {
  findOne(request: HeroById, metadata: Metadata, ...rest: any): Observable<Hero>;

  array(request: Empty, metadata: Metadata, ...rest: any): Observable<HeroArray>;

  findMany(request: HeroById, metadata: Metadata, ...rest: any): Observable<HeroArray>;

  nested(request: Empty, metadata: Metadata, ...rest: any): Observable<nestedType>;

  enum(request: Empty, metadata: Metadata, ...rest: any): Observable<EnumType>;

  getFirstCommand(
    request: getFirstCommandRequest,
    metadata: Metadata,
    ...rest: any
  ): Observable<getFirstCommandResponse>;

  getFirstquery(request: getFirstqueryRequest, metadata: Metadata, ...rest: any): Observable<getFirstqueryResponse>;
}

export interface PROJECT1ServiceController {
  findOne(request: HeroById, metadata: Metadata, ...rest: any): Promise<Hero> | Observable<Hero> | Hero;

  array(request: Empty, metadata: Metadata, ...rest: any): Promise<HeroArray> | Observable<HeroArray> | HeroArray;

  findMany(request: HeroById, metadata: Metadata, ...rest: any): Promise<HeroArray> | Observable<HeroArray> | HeroArray;

  nested(request: Empty, metadata: Metadata, ...rest: any): Promise<nestedType> | Observable<nestedType> | nestedType;

  enum(request: Empty, metadata: Metadata, ...rest: any): Promise<EnumType> | Observable<EnumType> | EnumType;

  getFirstCommand(
    request: getFirstCommandRequest,
    metadata: Metadata,
    ...rest: any
  ): Promise<getFirstCommandResponse> | Observable<getFirstCommandResponse> | getFirstCommandResponse;

  getFirstquery(
    request: getFirstqueryRequest,
    metadata: Metadata,
    ...rest: any
  ): Promise<getFirstqueryResponse> | Observable<getFirstqueryResponse> | getFirstqueryResponse;
}

export function PROJECT1ServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "findOne",
      "array",
      "findMany",
      "nested",
      "enum",
      "getFirstCommand",
      "getFirstquery",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PROJECT1Service", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PROJECT1Service", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROJECT1_SERVICE_NAME = "PROJECT1Service";
