// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: AUTH_SVC/AUTH_SVC.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

/** hero/hero.proto */

export interface logInRequest {
  userName: string;
  password: string;
}

export interface logInResponse {
  data: logInData | undefined;
  message: string;
  error: string[];
  status: number;
}

export interface logInData {
  token: string;
}

export interface AUTHServiceClient {
  logIn(request: logInRequest, metadata: Metadata, ...rest: any): Observable<logInResponse>;
}

export interface AUTHServiceController {
  logIn(
    request: logInRequest,
    metadata: Metadata,
    ...rest: any
  ): Promise<logInResponse> | Observable<logInResponse> | logInResponse;
}

export function AUTHServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["logIn"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AUTHService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AUTHService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AUTHService";
